## Docker testing image for Metal
FROM node:24.13.0-slim
LABEL org.opencontainers.image.authors="Anis Megdiche <anis.megdiche@gmail.com>"

# Update packages
RUN apt-get update && apt-get upgrade -y

# Create the app directory
WORKDIR /app

# Copy dependency and config files
# folders
COPY src ./src
COPY config ./config
RUN mkdir -p tmp/data
RUN mkdir -p tmp/models
# files
COPY package.json ./
COPY tsconfig.json ./
COPY tsup.config.ts ./
COPY vitest* ./
COPY *.md ./

# Install dependencies
RUN npm install

# Start your app (you can change this to whatever you use to start the container)
CMD ["npm", "run", "test"]