## Docker testing image for Metal
FROM node:24.13.0-slim
LABEL org.opencontainers.image.authors="Anis Megdiche <anis.megdiche@gmail.com>"

# Update packages
RUN apt-get update && apt-get upgrade -y

# Create the app directory
RUN mkdir -p /app
WORKDIR /app

COPY src /app/src
COPY package.json /app
COPY tsconfig.json /app
COPY *.md /app
COPY jest* /app

RUN npm install
RUN npm run prepare

# Start your app (you can change this to whatever you use to start the container)
CMD ["npm", "run", "test"]