###
# @name login
POST  http://127.0.0.1:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}

###
@token={{login.response.body.token}}

###
# @name get-plan
GET http://127.0.0.1:3000/schema/aiplan/img2class
Content-Type: application/json
authorization: Bearer {{token}}
