//
//
//

//
export enum LANG_ISO {
	af_ZA = "af_ZA",
	ar_AR = "ar_AR",
	az_AZ = "az_AZ",
	bn_IN = "bn_IN",
	cs_CZ = "cs_CZ",
	de_DE = "de_DE",
	en_XX = "en_XX",
	es_XX = "es_XX",
	et_EE = "et_EE",
	fa_IR = "fa_IR",
	fi_FI = "fi_FI",
	fr_XX = "fr_XX",
	gl_ES = "gl_ES",
	gu_IN = "gu_IN",
	he_IL = "he_IL",
	hi_IN = "hi_IN",
	hr_HR = "hr_HR",
	id_ID = "id_ID",
	it_IT = "it_IT",
	ja_XX = "ja_XX",
	ka_GE = "ka_GE",
	kk_KZ = "kk_KZ",
	km_KH = "km_KH",
	ko_KR = "ko_KR",
	lt_LT = "lt_LT",
	lv_LV = "lv_LV",
	mk_MK = "mk_MK",
	ml_IN = "ml_IN",
	mn_MN = "mn_MN",
	mr_IN = "mr_IN",
	my_MM = "my_MM",
	ne_NP = "ne_NP",
	nl_XX = "nl_XX",
	pl_PL = "pl_PL",
	ps_AF = "ps_AF",
	pt_XX = "pt_XX",
	ro_RO = "ro_RO",
	ru_RU = "ru_RU",
	si_LK = "si_LK",
	sl_SI = "sl_SI",
	sv_SE = "sv_SE",
	sw_KE = "sw_KE",
	ta_IN = "ta_IN",
	te_IN = "te_IN",
	th_TH = "th_TH",
	tl_XX = "tl_XX",
	tr_TR = "tr_TR",
	uk_UA = "uk_UA",
	ur_PK = "ur_PK",
	vi_VN = "vi_VN",
	xh_ZA = "xh_ZA",
	zh_CN = "zh_CN",
}
