version: "0.1"
server:
  port: 3000
  verbosity: debug
  timezone: UTC
  authentication:
  request-limit: 100mb
  cache:
    provider: mongodb
    host: mongodb://localhost:27017/
    database: metal_cache
    options:
      connectTimeoutMS: 5000
      serverSelectionTimeoutMS: 5000

users:
  myapiuser: myStr@ngpa$$w0rd

sources:
  fs-json-data:
    provider: files
    database: ./data/
    options:
      storageType: filesystem
      contentType: json
      jsonArrayPath: rows
  fs-csv-data:
    provider: files
    database: ./data/
    options:
      storageType: filesystem
      contentType: csv
      csvDelimiter: ','
      csvNewline: "\n"
      csvHeader: true
      csvQuoteChar: '"'
  az-json-data:
    provider: files
    host: UseDevelopmentStorage=true
    database: datacontainer1
    options:
      storageType: azureblob
      contentType: json

schemas:
  fsjson:
    sourceName: fs-json-data
  fscsv:
    sourceName: fs-csv-data
  azjson:
    sourceName: az-json-data
  # azcsv:
  #   sourceName: fs-csv-data
