version: "0.5"

server:
  port: 3000
  verbosity: debug
  timezone: UTC
  request-limit: 100mb
  response-limit: 100mb
  authentication:
    provider: local
    default-role: all
  cache:
    provider: memory
    database: cache
    options:
      autocreate: true
  ai-engines:
    # docker-url:
    engines-url: http://localhost:5000

roles:
  all: lacrud

users:
  myapiuser:
    password: myStr@ngpa$$w0rd

sources:
  src-fs:
    provider: folder
    options:
      storage-type: fs
      fs-folder: ./data/
  src-myplan:
    provider: plan
    database: myplan

schemas:
  fs:
    source: src-fs
  myplan:
    source: src-myplan

schedules:
  "p1":
    plan: myplan
    entity: myentity
    cron: "*/1 * * * *"
  "p2":
    plan: myplan
    entity: myentity
    cron: "@start"

plans:
  myplan:
    myentity:
      - select:
          schema: fs
          entity: audio

      - run:
          ai: audio
          task: audio-classification
          input: content

      - run:
          ai: audio
          task: automatic-speech-recognition
          input: content
          output: text

      - omit: [content]
