version: "0.2"
server:
  port: 3000
  verbosity: debug
  timezone: UTC
  authentication:
  request-limit: 100mb
  cache:
    provider: mongodb
    host: mongodb://localhost:27017/
    database: metal_cache
    options:
      connectTimeoutMS: 5000
      serverSelectionTimeoutMS: 5000

users:
  myapiuser: myStr@ngpa$$w0rd

sources:
  fs-json-data:
    provider: files
    options:
      storageType: filesystem
      contentType: json
      fsFolder: ./data/
      jsonArrayPath: rows
  fs-csv-data:
    provider: files
    options:
      storageType: filesystem
      contentType: csv
      fsFolder: ./data/
      csvDelimiter: ','
      csvNewline: "\n"
      csvHeader: true
      csvQuoteChar: '"'
  az-json-data:
    provider: files
    options:
      storageType: azureblob
      contentType: json
      azureBlobConnectionString: UseDevelopmentStorage=true
      azureBlobContainerName: datacontainer1
  az-csv-data:
    provider: files
    options:
      storageType: azureblob
      contentType: csv
      azureBlobConnectionString: UseDevelopmentStorage=true
      azureBlobContainerName: datacontainer1
      csvDelimiter: ','
      csvNewline: "\n"
      csvHeader: true
      csvQuoteChar: '"'


schemas:
  fsjson:
    sourceName: fs-json-data
  fscsv:
    sourceName: fs-csv-data
  azjson:
    sourceName: az-json-data
  azcsv:
    sourceName: az-csv-data
