version: "0.3"
server:
  port: 3000
  verbosity: debug
  timezone: UTC
  authentication:
  request-limit: 100mb
  cache:
    provider: mongodb
    host: mongodb://localhost:27017/
    database: metal_cache
    options:
      connectTimeoutMS: 5000
      serverSelectionTimeoutMS: 5000

users:
  myapiuser: myStr@ngpa$$w0rd

sources:
  fs-json-data:
    provider: files
    options:
      storage: fs
      type: json
      fs-folder: ./data/
      json-path: rows
  fs-csv-data:
    provider: files
    options:
      storage: fs
      type: csv
      fs-folder: ./data/
      csv-delimiter: ','
      csv-newline: "\n"
      csv-header: true
      csv-quote: '"'
  az-json-data:
    provider: files
    options:
      storage: az-blob
      type: json
      az-blob-connection-string: UseDevelopmentStorage=true
      az-blob-container: datacontainer1
  az-csv-data:
    provider: files
    options:
      storage: az-blob
      type: csv
      az-blob-connection-string: UseDevelopmentStorage=true
      az-blob-container: datacontainer1
      csv-delimiter: ','
      csv-newline: "\n"
      csv-header: true
      csv-quote: '"'


schemas:
  fsjson:
    source: fs-json-data
  fscsv:
    source: fs-csv-data
  azjson:
    source: az-json-data
  azcsv:
    source: az-csv-data
