version: "0.5"

server:
  port: 3000
  verbosity: debug
  timezone: UTC
  request-limit: 100mb
  authentication:
    provider: local
    default-role: all
  cache:
    provider: memory
    database: cache
    options:
      autocreate: true

roles:
  all: lacrud

users:
  myapiuser:
    password: myStr@ngpa$$w0rd

sources:
  src-fs:
    provider: storage
    options:
      storage-mode: files
      storage-type: fs
      fs-folder: ./data/
      content:
        "homes*.csv":
          content-type: csv
          csv-delimiter: ", "
          csv-newline: "\n"
          csv-header: true
          csv-quote: '"'
        "industry*.csv":
          content-type: csv
          csv-delimiter: ","
          csv-newline: "\r\n"
          csv-header: true
          csv-quote: '"'
        "ref*.xlsx":
          content-type: xls
          xls-sheet: Feuil1
        "sample*.xlsx":
          content-type: xls
          xls-starting-cell: E6
  src-azure-blob:
    provider: storage
    options:
      storage-mode: files
      storage-type: azure-blob
      connection-string: UseDevelopmentStorage=true
      container: datacontainer1
      content:
        "*.json":
          content-type: json
          json-path: rows
        "*.csv":
          content-type: csv
          csv-delimiter: ","
          csv-newline: "\n"
          csv-header: true
          csv-quote: '"'

schemas:
  fs:
    source: src-fs
  azure-blob:
    source: src-azure-blob
