version: "0.5"
server:
  verbosity: debug
  port: 3000
  request-limit: 100mb
  authentication:
    provider: local
    default-role: all

roles:
  all: lacrud

users:
  myapiuser:
    password: myStr@ngpa$$w0rd

sources:
  metal-northwind:
    provider: metal
    host: http://127.0.0.1:3001
    user: myapiuser
    password: myStr@ngpa$$w0rd
    database: northwind

schemas:
  metalws:
    source: metal-northwind
