version: "0.3"

server:
  port: 3000
  verbosity: debug
  timezone: UTC
  request-limit: 100mb
  authentication:
    provider: local
    default-role: all
  cache:
    provider: memory
    database: cache
    options:
      autocreate: true

roles:
  all: lacrud
  none:

users:
  myapiuser:
    password: myStr@ngpa$$w0rd

sources:
  src-mem:
    provider: memory
    database: memory
    options:
      autocreate: true

  src-ws-noauth:    # https://fakerestapi.azurewebsites.net/index.html
    provider: webservice
    host: https://fakerestapi.azurewebsites.net/api/v1/
    options:
      type: rest
      content: json
      endpoints:
        collection:
          read: GET
        item:
          read: GET:/@{id}
          create: POST
          update: PUT:/@{id}
          delete: DELETE:/@{id}
      
  src-ws-auth:    # https://dummyjson.com/docs
    provider: webservice
    host: https://dummyjson.com/
    options:
      type: rest
      content: json
      json-path: ${{ $entity }}
      endpoints:
        login: 
          url: POST:/user/login
          body:
            username: emilys
            password: emilyspass
          headers:
            Authorization: "Bearer: ${{ $body.accessToken }}"
        collection:
          read: GET
        item:
          read: GET:/@{id}
          create: POST:/add
          update: PUT:/@{id}
          delete: DELETE:/@{id}

schemas:
  ws1:
    source: src-ws-noauth
  ws2:
    source: src-ws-auth