version: "0.3"
server:
  port: 3000
  verbosity: debug
  timezone: UTC
  authentication:
  request-limit: 100mb

users:
  myapiuser: myStr@ngpa$$w0rd

sources:
  pg-clubdata-members:
    provider: postgres
    host: localhost
    port: 5436
    user: admin
    password: "123456"
    database: clubdata    
  mem-data:
    provider: memory
  plan-sync:
    provider: plan
    database: sync

schemas:
  mem:
    sourceName: mem-data
    entities:
      syncdown:
        sourceName: plan-sync
        entityName: members-down
  pg:
    sourceName: pg-clubdata-members

schedules:
  start:
    cron: "@start"
    planName: sync
    entityName: members-up

plans:
  sync:
    members-up:
      - sync:
          source:
            schema: pg
            entityName: members
          destination:
            schema: mem
            entityName: members
          on: memid

      - update:
          schema: mem
          entityName: members
          data:
            address: XXXXXXXXXX
    
      - sync:
          source:
            schema: mem
            entityName: members
          destination:
            schema: pg
            entityName: members
          on: memid
    members-down:
      - sync:
          source:
            schema: mem
            entityName: members
          destination:
            schema: pg
            entityName: members
          on: memid