version: "0.1"
server:
  port: 3000
  verbosity: debug
  timezone: UTC
  authentication:
  request-limit: 100mb
  cache:
    provider: mongodb
    host: mongodb://localhost:27017/
    database: metal_cache
    options:
      connectTimeoutMS: 5000
      serverSelectionTimeoutMS: 5000

users:
  myapiuser: myStr@ngpa$$w0rd

sources:
  ms-hr:
    provider: mssql
    host: localhost
    port: 1433
    user: sa
    password: Azerty123!
    database: hr
  mdb-mflix:
    provider: mongodb
    host: mongodb://localhost:27017/
    database: mflix
    options:
      connectTimeoutMS: 5000
      serverSelectionTimeoutMS: 5000
  pg-northwind:
    provider: postgres
    host: localhost
    port: 5432
    user: admin
    password: "123456"
    database: northwind
  pg-clubdata:
    provider: postgres
    host: localhost
    port: 5433
    user: admin
    password: "123456"
    database: clubdata
  pg-clubdata-bookings:
    provider: postgres
    host: localhost
    port: 5434
    user: admin
    password: "123456"
    database: clubdata
  pg-clubdata-facilities:
    provider: postgres
    host: localhost
    port: 5435
    user: admin
    password: "123456"
    database: clubdata
  pg-clubdata-members:
    provider: postgres
    host: localhost
    port: 5436
    user: admin
    password: "123456"
    database: clubdata
  plan-etl1:
    provider: plan
    database: etl1

schemas:
  northwind:
    sourceName: pg-northwind
  hr:
    sourceName: ms-hr
  mflix:
    sourceName: mdb-mflix
  clubdata:
    entities:
      members:
        sourceName: pg-clubdata-members
        entityName: members
      facilities:
        sourceName: pg-clubdata-facilities
        entityName: facilities
      bookings:
        sourceName: pg-clubdata-bookings
        entityName: bookings
  merge:
    sourceName: pg-clubdata
    entities:
      orders:
        sourceName: pg-northwind
        entityName: orders
      users:
        sourceName: mdb-mflix
        entityName: users
  sch-etl1:
    sourceName: plan-etl1

schedules:
  run entity contact of my etl1 plan:
    planName: etl1
    entityName: contact
    cron: "* */5 * * * *"

ai-engines:
  ocr:
    engine: tesseractjs
    model: eng
  image-classify:
    engine: tensorflowjs
    model: image-classify
  sentiment:
    engine: nlpjs
    model: sentiment
    options:
      lang: en
  guess-lang:
    engine: nlpjs
    model: guess-lang
    options:
      accept: en,fr

plans:
  etl1:
    src:
      - insert:
          data:
            - img_to_text: https://tesseract.projectnaptha.com/img/eng_bw.png
              img_to_classify: https://thumbs.dreamstime.com/b/isolated-classical-guitar-photo-png-format-available-full-transparent-background-54363220.jpg
            - img_to_text: https://jeroen.github.io/images/testocr.png
              img_to_classify: https://img.freepik.com/premium-photo/golden-retriever-lying-panting-isolated-white_191971-16974.jpg
            - img_to_text: https://www.srcmake.com/uploads/5/3/9/0/5390645/ocr_orig.png
              img_to_classify: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPpDgjJjrakUj3VlDC0K6XtdCRu5TK7CPXr7QHVjiL&s

    aitest2:
      - debug:
      - select:
          schemaName: mflix
          entityName: movies
          filter:
            year: 2001
          fields: title
      - run:
          ai: sentiment
          input: title
          output:
            vote: sentiment
    aitest:
      - debug:
      - insert:
          data:
            - img_to_text: https://tesseract.projectnaptha.com/img/eng_bw.png
              img_to_classify: https://thumbs.dreamstime.com/b/isolated-classical-guitar-photo-png-format-available-full-transparent-background-54363220.jpg
            - img_to_text: https://jeroen.github.io/images/testocr.png
              img_to_classify: https://img.freepik.com/premium-photo/golden-retriever-lying-panting-isolated-white_191971-16974.jpg
            - img_to_text: https://www.srcmake.com/uploads/5/3/9/0/5390645/ocr_orig.png
              img_to_classify: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPpDgjJjrakUj3VlDC0K6XtdCRu5TK7CPXr7QHVjiL&s
      - run:
          ai: ocr
          input: img_to_text
          output:
            confidence: ocr_confidence
            text: ocr_text
      - run:
          ai: image-classify
          input: img_to_classify
          output:
            class: object
      - run:
          ai: sentiment
          input: ocr_text
          output: sentiment
      - run:
          ai: guess-lang
          input: ocr_text
          output:

    contact:
      - debug:
      - select:
          schemaName: demo
          entityName: res_partner
          fields: id, name, display_name
      - addField:
          name: quality
          type: integer
      - sort:
          id:
      - update:
          filterExpression: "id < 10"
          data:
            name: "AAA"
            display_name: "BBB"
      - delete:
          filterExpression: "id >= 100"
      - insert:
          data:
            name: John
            display_name: Mr. John Doe
      # - bad-step-test3: "***TEST***"

    login:
      - debug:
      - select:
          schemaName: demo
          entityName: res_users
          fields: login, partner_id
      # - bad-step-test1: "***TEST***"
      # - break: step by step test
      - join:
          type: left
          entityName: contact
          leftField: partner_id
          rightField: id
      - fields: id, name, login
      # - debug:
      - sort:
          login: asc
          name: desc
      # - bad-step-test2: "***TEST***"
      - insert:
          schemaName: demo
          entityName: res_users
      - delete:
          schemaName: demo
          entityName: res_users
          filter:
            lang: fr_FR
