services:

  #
  # Base Image (Build this first: docker-compose build base)
  #
  base-text:
    image: metal-ai-engine-base-text:1.0.0
    build: ./services/base/text

  base-image:
    image: metal-ai-engine-base-image:1.0.0
    build: ./services/base/image

  #
  # Text
  #

  text-emotion-detection:
    build: ./services/text/emotion-detection
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5101:5000"
    volumes:
      - ./services/text/emotion-detection:/app
      - metal-model-cache:/data/models

  text-feature-extraction:
    build: ./services/text/feature-extraction
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5102:5000"
    volumes:
      - ./services/text/feature-extraction:/app
      - metal-model-cache:/data/models

  text-fill-mask:
    build: ./services/text/fill-mask
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5103:5000"
    volumes:
      - ./services/text/fill-mask:/app
      - metal-model-cache:/data/models

  text-keyword-extraction:
    build: ./services/text/keyword-extraction
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5104:5000"
    volumes:
      - ./services/text/keyword-extraction:/app
      - metal-model-cache:/data/models

  text-language-detection:
    build: ./services/text/language-detection
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5105:5000"
    volumes:
      - ./services/text/language-detection:/app
      - metal-model-cache:/data/models

  text-paraphrase-detection:
    build: ./services/text/paraphrase-detection
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5106:5000"
    volumes:
      - ./services/text/paraphrase-detection:/app
      - metal-model-cache:/data/models

  text-question-answering:
    build: ./services/text/question-answering
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5107:5000"
    volumes:
      - ./services/text/question-answering:/app
      - metal-model-cache:/data/models

  text-sentence-similarity:
    build: ./services/text/sentence-similarity
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5108:5000"
    volumes:
      - ./services/text/sentence-similarity:/app
      - metal-model-cache:/data/models

  text-sentiment-analysis:
    build: ./services/text/sentiment-analysis
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5109:5000"
    volumes:
      - ./services/text/sentiment-analysis:/app
      - metal-model-cache:/data/models

  text-summarization:
    build: ./services/text/summarization
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5110:5000"
    volumes:
      - ./services/text/summarization:/app
      - metal-model-cache:/data/models

  # text-text2text-generation:
  #   build: ./services/text/text2text-generation
  #   command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
  #   ports:
  #     - "5111:5000"
  #   volumes:
  #     - ./services/text/text2text-generation:/app
  #     - metal-model-cache:/data/models

  text-text-generation:
    build: ./services/text/text-generation
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5112:5000"
    volumes:
      - ./services/text/text-generation:/app
      - metal-model-cache:/data/models

  text-ner:
    build: ./services/text/ner
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5113:5000"
    volumes:
      - ./services/text/ner:/app
      - metal-model-cache:/data/models

  text-toxicity-detection:
    build: ./services/text/toxicity-detection
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5114:5000"
    volumes:
      - ./services/text/toxicity-detection:/app
      - metal-model-cache:/data/models

  text-translation:
    build: ./services/text/translation
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5115:5000"
    volumes:
      - ./services/text/translation:/app
      - metal-model-cache:/data/models

  text-zero-shot-classification:
    build: ./services/text/zero-shot-classification
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5116:5000"
    volumes:
      - ./services/text/zero-shot-classification:/app
      - metal-model-cache:/data/models

  #
  # Ocr
  #
    
  ocr:
    build: ./services/ocr
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5201:5000"
    volumes:
      - ./services/ocr:/app
      - metal-model-cache:/data/models

  #
  # Image
  #

  # image-depth-estimation:
  #   build: ./services/image/depth-estimation
  #   command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
  #   ports:
  #     - "5301:5000"
  #   volumes:
  #     - ./services/image/depth-estimation:/app
  #     - metal-model-cache:/data/models

  image-image-classification:
    build: ./services/image/image-classification
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5302:5000"
    volumes:
      - ./services/image/image-classification:/app
      - metal-model-cache:/data/models

  image-image-segmentation:
    build: ./services/image/image-segmentation
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5303:5000"
    volumes:
      - ./services/image/image-segmentation:/app
      - metal-model-cache:/data/models

  image-image-to-text:
    build: ./services/image/image-to-text
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5304:5000"
    volumes:
      - ./services/image/image-to-text:/app
      - metal-model-cache:/data/models

  image-object-detection:
    build: ./services/image/object-detection
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5305:5000"
    volumes:
      - ./services/image/object-detection:/app
      - metal-model-cache:/data/models

  image-visual-question-answering:
    build: ./services/image/visual-question-answering
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5306:5000"
    volumes:
      - ./services/image/visual-question-answering:/app
      - metal-model-cache:/data/models

#
# Audio
#

  audio-audio-classification:
    build: ./services/audio/audio-classification
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5401:5000"
    volumes:
      - ./services/audio/audio-classification:/app
      - metal-model-cache:/data/models

  audio-automatic-speech-recognition:
    build: ./services/audio/automatic-speech-recognition
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5402:5000"
    volumes:
      - ./services/audio/automatic-speech-recognition:/app
      - metal-model-cache:/data/models

volumes:
  metal-model-cache: