
# Base URL
@apiUrl = http://localhost

# @name image-apis
# Common variables
@car1 = car1.jpg
@photo1 = photo1.jpeg
@photo2 = photo2.jpeg
@city1 = city1.jpg


# //XXX to remove from catalogue
# ### @name depth-estimation
# POST {{apiUrl}}:5301/image-depth-estimation/run
# Content-Type: multipart/form-data; boundary=image

# --image
# Content-Disposition: form-data; name="file"; filename="{{photo1}}"
# Content-Type: image/jpeg

# < ../data/pic/{{photo1}}
# --image--


### @name image-classification
POST {{apiUrl}}:5302/image-image-classification/run
Content-Type: multipart/form-data; boundary=image

--image
Content-Disposition: form-data; name="file"; filename="{{car1}}"
Content-Type: image/jpeg

< ../data/pic/{{car1}}
--image--

# Response
# {
#   "result": [
#     {
#       "label": "sports car, sport car",
#       "score": 0.9760120511054993
#     },
#     {
#       "label": "car wheel",
#       "score": 0.0069635119289159775
#     },
#     {
#       "label": "racer, race car, racing car",
#       "score": 0.005621959920972586
#     },
#     {
#       "label": "convertible",
#       "score": 0.0052965302020311356
#     },
#     {
#       "label": "grille, radiator grille",
#       "score": 0.004549334291368723
#     }
#   ]
# }


### @name image-segmentation
POST {{apiUrl}}:5303/image-image-segmentation/run
Content-Type: multipart/form-data; boundary=image

--image
Content-Disposition: form-data; name="file"; filename="{{city1}}"
Content-Type: image/jpeg

< ../data/pic/{{city1}}
--image--

# Response
# {
#   "masks": [
#     {
#       "score": null,
#       "label": "sidewalk",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "person",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "earth",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "path",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "streetlight",
#       "mask": "<base64>"
#     }
#   ],
#   "model": "nvidia/segformer-b0-finetuned-ade-512-512"
# }

### @name object-detection
POST {{apiUrl}}:5305/image-object-detection/run
Content-Type: multipart/form-data; boundary=image

--image
Content-Disposition: form-data; name="file"; filename="{{city1}}"
Content-Type: image/jpeg

< ../data/pic/{{city1}}
--image--

# Response
# {
#   "result": [
#     {
#       "score": 0.9995905756950378,
#       "label": "person",
#       "box": {
#         "xmin": 2243,
#         "ymin": 761,
#         "xmax": 2529,
#         "ymax": 1656
#       }
#     },
#     {
#       "score": 0.9221118092536926,
#       "label": "sports ball",
#       "box": {
#         "xmin": 677,
#         "ymin": 636,
#         "xmax": 738,
#         "ymax": 699
#       }
#     },
#     {
#       "score": 0.9524379968643188,
#       "label": "sports ball",
#       "box": {
#         "xmin": 928,
#         "ymin": 581,
#         "xmax": 999,
#         "ymax": 661
#       }
#     },
#     {
#       "score": 0.9995604157447815,
#       "label": "person",
#       "box": {
#         "xmin": 608,
#         "ymin": 856,
#         "xmax": 1017,
#         "ymax": 1479
#       }
#     },
#     {
#       "score": 0.9947951436042786,
#       "label": "person",
#       "box": {
#         "xmin": 1287,
#         "ymin": 622,
#         "xmax": 1699,
#         "ymax": 1832
#       }
#     },
#     {
#       "score": 0.731742799282074,
#       "label": "sports ball",
#       "box": {
#         "xmin": 605,
#         "ymin": 632,
#         "xmax": 668,
#         "ymax": 704
#       }
#     },
#     {
#       "score": 0.5397851467132568,
#       "label": "handbag",
#       "box": {
#         "xmin": 2407,
#         "ymin": 1134,
#         "xmax": 2465,
#         "ymax": 1284
#       }
#     },
#     {
#       "score": 0.9984428286552429,
#       "label": "person",
#       "box": {
#         "xmin": 1720,
#         "ymin": 826,
#         "xmax": 1926,
#         "ymax": 1442
#       }
#     }
#   ]
# }

### @name image-to-text
POST {{apiUrl}}:5304/image-image-to-text/run
Content-Type: multipart/form-data; boundary=image

--image
Content-Disposition: form-data; name="file"; filename="{{photo1}}"
Content-Type: image/jpeg

< ../data/pic/{{photo1}}
--image--

# Response
# {
#   "result": [
#     {
#       "generated_text": "a person is holding a laptop computer and a camera "
#     }
#   ]
# }


### @name visual-question-answering
POST {{apiUrl}}:5306/image-visual-question-answering/run
Content-Type: multipart/form-data; boundary=image

--image
Content-Disposition: form-data; name="file"; filename="{{photo1}}"
Content-Type: image/jpeg

< ../data/pic/{{photo1}}

--image
Content-Disposition: form-data; name="request"

{
  "question": "What is in this image?"
}
--image--

# Response
# {
#   "result": [
#     {
#       "label": "sports car, sport car",
#       "score": 0.9760120511054993
#     },
#     {
#       "label": "car wheel",
#       "score": 0.006963498890399933
#     },
#     {
#       "label": "racer, race car, racing car",
#       "score": 0.005621954798698425
#     },
#     {
#       "label": "convertible",
#       "score": 0.005296570248901844
#     },
#     {
#       "label": "grille, radiator grille",
#       "score": 0.004549334291368723
#     }
#   ]
# }
