
# Base URL
@apiUrl = http://localhost

# @name image-apis
# Common variables
@car1 = car1.jpg
@photo1 = photo1.jpeg
@photo2 = photo2.jpeg
@city1 = city1.jpg


# //XXX to remove from catalogue
# ### @name depth-estimation
# POST {{apiUrl}}:5301/image-depth-estimation/run
# Content-Type: multipart/form-data; boundary=image

# --image
# Content-Disposition: form-data; name="input_data"; filename="{{photo1}}"
# Content-Type: image/jpeg

# < ../data/pic/{{photo1}}
# --image--


### @name image-classification-health
GET {{apiUrl}}:5302/image-image-classification/health
Content-Type: application/json


### @name image-classification
POST {{apiUrl}}:5302/image-image-classification/run
Content-Type: application/json

< ../data/b64/photo1.jpeg.b64

# Request
# {
#   "input_data": "<base64>"
# }

# Response
# {
#   "result": [
#     {
#       "label": "reflex camera",
#       "score": 0.20496124029159546
#     },
#     {
#       "label": "notebook, notebook computer",
#       "score": 0.12176289409399033
#     },
#     {
#       "label": "desktop computer",
#       "score": 0.10481187701225281
#     },
#     {
#       "label": "Polaroid camera, Polaroid Land camera",
#       "score": 0.055222440510988235
#     },
#     {
#       "label": "screen, CRT screen",
#       "score": 0.0461791455745697
#     }
#   ]
# }


### @name image-segmentation
POST {{apiUrl}}:5303/image-image-segmentation/run
Content-Type: application/json

< ../data/b64/photo1.jpeg.b64

# Request
# {
#   "input_data": "<base64>"
# }

# Response
# {
#   "masks": [
#     {
#       "score": null,
#       "label": "wall",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "chair",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "car",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "desk",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "box",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "signboard",
#       "mask": "<base64>"
#     },
#     {
#       "score": null,
#       "label": "computer",
#       "mask": "<base64>"
#     }
#   ],
#   "model": "nvidia/segformer-b0-finetuned-ade-512-512"
# }


### @name image-to-text
POST {{apiUrl}}:5304/image-image-to-text/run
Content-Type: application/json

< ../data/b64/photo1.jpeg.b64

# Request
# {
#   "input_data": "<base64>"
# }

# Response
# {
#   "result": [
#     {
#       "generated_text": "a person is holding a laptop computer and a camera "
#     }
#   ]
# }


### @name object-detection
POST {{apiUrl}}:5305/image-object-detection/run
Content-Type: application/json

< ../data/b64/photo1.jpeg.b64

# Request
# {
#   "input_data": "<base64>"
# }

# Response
# {
#   "result": [
#     {
#       "score": 0.9758986234664917,
#       "label": "person",
#       "box": {
#         "xmin": 849,
#         "ymin": 298,
#         "xmax": 1343,
#         "ymax": 998
#       }
#     },
#     {
#       "score": 0.7706025838851929,
#       "label": "person",
#       "box": {
#         "xmin": 851,
#         "ymin": 299,
#         "xmax": 1343,
#         "ymax": 899
#       }
#     },
#     {
#       "score": 0.9996515512466431,
#       "label": "laptop",
#       "box": {
#         "xmin": 312,
#         "ymin": 118,
#         "xmax": 1223,
#         "ymax": 857
#       }
#     },
#     {
#       "score": 0.9554157853126526,
#       "label": "dining table",
#       "box": {
#         "xmin": 0,
#         "ymin": 194,
#         "xmax": 1343,
#         "ymax": 994
#       }
#     },
#     {
#       "score": 0.5615569353103638,
#       "label": "keyboard",
#       "box": {
#         "xmin": 404,
#         "ymin": 611,
#         "xmax": 1185,
#         "ymax": 755
#       }
#     }
#   ]
# }


### @name visual-question-answering
POST {{apiUrl}}:5306/image-visual-question-answering/run
Content-Type: application/json

< ../data/b64/city1.jpg.b64

# Request
# {
#   "params": {
#     "question": "How many people?"
#   },
#   "input_data": "<base64>"
# }

# Response
# {
#   "result": [
#     {
#       "score": 0.585539698600769,
#       "answer": "4"
#     },
#     {
#       "score": 0.4101852476596832,
#       "answer": "3"
#     },
#     {
#       "score": 0.2669353485107422,
#       "answer": "5"
#     },
#     {
#       "score": 0.04362616688013077,
#       "answer": "6"
#     },
#     {
#       "score": 0.005054139532148838,
#       "answer": "7"
#     }
#   ]
# }
