# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}
###


@token={{login.response.body.token}}
###


# FIX: datatable has uppercase  letters in Fields, Rows & Meta
# @name add-some-data
GET http://localhost:3000/schema/mflix/users
    ?filter={"country":"France","name":"John"}
    &cache="100"
authorization: Bearer {{token}}
Content-Type: application/json
###


# DONE
# @name view
GET http://localhost:3000/cache/view
authorization: Bearer {{token}}
###


# DONE
# @name purge
POST http://localhost:3000/cache/purge
authorization: Bearer {{token}}
###


# DONE
# @name clean
POST http://localhost:3000/cache/clean
authorization: Bearer {{token}}