# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}
###


@token={{login.response.body.token}}
###
###### FS   ######

# @name list
GET http://localhost:3000/schema/fsjson
authorization: Bearer {{token}}
###

# @name select
GET http://localhost:3000/schema/fsjson/customer.json
    # ?fields=city,country
    # &filter={"country":"France"}
    # &cache=300
authorization: Bearer {{token}}
###


GET http://localhost:3000/schema/fscsv/covid.csv
    ?fields=iso_code,continent,location
authorization: Bearer {{token}}
###


# @name patch_customer_json
PATCH  http://localhost:3000/schema/fsjson/customer.json
Content-Type: application/json
authorization: Bearer {{token}}

{
    "filter": {
        "country" : "France"
    },
    "data": {
        "city": "XXXXXXXXXX"
    }
}
###
###### AZURE BLOB   ######

# @name list
GET http://localhost:3000/schema/azjson
authorization: Bearer {{token}}
###


# @name select
GET http://localhost:3000/schema/azjson/colors.json
    ?filter-expression=hexcode LIKE '%%00'
authorization: Bearer {{token}}
###


GET http://localhost:3000/schema/azcsv/addresses.csv
    # ?filter-expression=hexcode LIKE '%%00'
authorization: Bearer {{token}}
###


PATCH  http://localhost:3000/schema/azcsv/addresses.csv
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
        "Country": "USA"
    }
}

###


# @name xls-list
GET http://localhost:3000/schema/fs
authorization: Bearer {{token}}
###


# @name xls-select
GET http://localhost:3000/schema/fs/sample.xlsx
   ?filter-expression=Name = 'Mary'
authorization: Bearer {{token}}
###


PATCH  http://localhost:3000/schema/fs/sample.xlsx
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
        "Country": "France",
        "City": "Paris"
    }
}

###
GET http://localhost:3000/schema/fs
authorization: Bearer {{token}}


###
GET http://localhost:3000/schema/fs/homes.csv
authorization: Bearer {{token}}


###
PATCH  http://localhost:3000/schema/fs/homes.csv
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
        "Country": "USA",
        "City": "New York"
    }
}


###
GET http://localhost:3000/schema/fs/industry_sic.csv
authorization: Bearer {{token}}