# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}
###


@token={{login.response.body.token}}
### 


# DONE
# @name list
GET http://localhost:3000/schema/mem
authorization: Bearer {{token}}
### 


# DONE
# @name select
GET http://localhost:3000/schema/mem/users
authorization: Bearer {{token}}
###


# DONE
# @name insert
POST http://localhost:3000/schema/mem/users
authorization: Bearer {{token}}
Content-Type: application/json

{
    "data": [
        {
                "name": "John Doe",
                "email": "j.doe@nowhere.com",
                "country": "France"
        },
        {
                "name": "Mary Jane",
                "email": "mary@somewhere.com",
                "country": "USA"
        }
    ]
}
###


# DONE
# @name get-cache
GET http://localhost:3000/schema/mem/users
    ?cache=3600
authorization: Bearer {{token}}
###


# DONE
# @name update
PATCH http://localhost:3000/schema/mem/users
authorization: Bearer {{token}}
Content-Type: application/json

{
    "filter-expression":"name like 'John%'",
    "data": {
                "city":"Paris"
    }
}
###


# DONE
# @name delete
DELETE http://localhost:3000/schema/mem/users
authorization: Bearer {{token}}
Content-Type: application/json