###
# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}

###
@token={{login.response.body.token}}

###
# @name select-users
GET http://localhost:3000/schema/mflix/users
    ?filter={"name":"Jaime Lannister"}
    &cache=300
Content-Type: application/json
authorization: Bearer {{token}}

###
# @name select-movies
GET http://localhost:3000/schema/mflix/movies
    ?filter={"year":1980}
Content-Type: application/json
authorization: Bearer {{token}}




####
# select
#

POST http://localhost:3000/schema/select/mflix/users
Content-Type: application/json

{
//    "fields": "name ,email ",
//    "sort": " name desc"
   "filter" :{
     "country":"France",
     "name": "john"
   },
   "cache": "10"
}