###
# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}

###
@token={{login.response.body.token}}

###
# @name ocr-test
GET http://localhost:3000/schema/sch-etl1/ocr
Content-Type: application/json
authorization: Bearer {{token}}


###
# @name get-plan
GET http://localhost:3000/schema/sch-etl1/aitest
Content-Type: application/json
authorization: Bearer {{token}}
