# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}
###


@token={{login.response.body.token}}
###


# DONE
# @name list-entities
GET http://localhost:3000/schema/clubdata
Content-Type: application/json
authorization: Bearer {{token}}
###


# DONE
# @name select
GET http://localhost:3000/schema/clubdata/members
Content-Type: application/json
authorization: Bearer {{token}}
###


# DONE
# @name select-filtered
GET http://localhost:3000/schema/clubdata/members
    ?fields=firstname, surname
    # &filter-expression=customer_id LIKE 'A%'
    &filter={"surname": "Smith"}
    &sort=firstname asc,surname desc
    &cache=300
Content-Type: application/json
authorization: Bearer {{token}}
###


# TODO
# @name insert-one
POST http://localhost:3000/schema/clubdata/members
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
      "memid": "1000",
      "firstname": "John",
      "surname": "Doe",
      "address": "GUEST",
      "zipcode": 0,
      "telephone": "(000) 000-0000",
      "recommendedby": null,
      "joindate": "2012-06-30T22:00:00.000Z"
    }
}
###


# TODO
# @name insert-many
POST http://localhost:3000/schema/clubdata/members
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": [
            {
      "memid": "1001",
      "firstname": "Joe",
      "surname": "Doe",
      "address": "GUEST",
      "zipcode": 0,
      "telephone": "(000) 000-0000",
      "recommendedby": null,
      "joindate": "2012-06-30T22:00:00.000Z"
    },{
      "memid": "1002",
      "firstname": "Jane",
      "surname": "Doe",
      "address": "GUEST",
      "zipcode": 0,
      "telephone": "(000) 000-0000",
      "recommendedby": null,
      "joindate": "2012-06-30T22:00:00.000Z"
    }
    ]
}
###


# TODO
# @name delete
DELETE http://localhost:3000/schema/clubdata/members
Content-Type: application/json
authorization: Bearer {{token}}

{
    "filerExpression": "customer_id like '%LLD'"
}