#
# login
#

# DONE
# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}

###

@token={{login.response.body.token}}

# DONE
# @name info
GET http://localhost:3000/server/info
Content-Type: application/json
authorization: Bearer {{token}}

###
# DONE
# @name reload
POST http://localhost:3000/server/reload
Content-Type: application/json
authorization: Bearer {{token}}

###
