# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}


###
@token={{login.response.body.token}}
###


# @name list
GET http://localhost:3000/schema/hr
authorization: Bearer {{token}}
###


# @name select
GET http://localhost:3000/schema/hr/countries
authorization: Bearer {{token}}
###


# @name select-filtered
GET http://localhost:3000/schema/hr/countries
    ?filterExpression=country_name LIKE '*a'
    &fields=country_id,country_name
    &sort=country_id asc,country_name desc
authorization: Bearer {{token}}
###


# @name insert-one
POST http://localhost:3000/schema/hr/countries
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
                "country_id":"XX",
                "country_name": "Nowhere Land",
                "region_id": 1
            }
}
###
