###
# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"admin",
    "password": 123456
}

###
@token={{login.response.body.token}}

###
# @name select
GET http://localhost:3000/schema/hr/dbo.countries
Content-Type: application/json
authorization: Bearer {{token}}
###

# @name select-filtered
GET http://localhost:3000/schema/hr/dbo.countries?filter-expression=country_name ~ '*a'&fields=country_id,country_name&sort=country_id asc,country_name desc
Content-Type: application/json
authorization: Bearer {{token}}

###
# @name insert-one
POST http://localhost:3000/schema/hr/dbo.countries
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
                "country_id":"XX",
                "country_name": "Nowhere Land",
                "region_id": 1
            }
}

#################################################################
###
# @name insert-many
POST http://localhost:3000/schema/insert/hr/dbo.countries
Content-Type: application/json

{
    "data": [
            {
                "last_name": "PLLD",
                "first_name": "Jane Poe",
                "last_name": "Poe LLD"
            },
            {
                "last_name": "LLLD",
                "first_name": "Larry Loe",
                "last_name": "Loe LLD"
            }
        ]
}


###
# U
POST http://localhost:3000/schema/update/hr/dbo.countries
Content-Type: application/json

{
    "filter-expression": "name ~ 'Tw*'",
    "data": {
        "color":5
    }
}

###
POST http://localhost:3000/m/hr/dbo.countries/delete
Content-Type: application/json

{
    "filter-expression": "name ~ 'Anis*' ",
    "fields": "name ,,,id",
    "sort": "name asc"
}
###

POST http://localhost:3000/m/hr/dbo.countries
Content-Type: application/json

{
      "Name": "Anissssss"
}
###
GET http://localhost:3000/m/hr/dbo.countries
###
DELETE http://localhost:3000/m/hr/dbo.countries/name/Anis
###
PATCH http://localhost:3000/m/hr/dbo.countries/name/8
Content-Type: application/json

{
    "name" : "Anis",
    "color" : "8"
}
###
###
### MongoDb
GET http://localhost:3000/m/mflix/users

### MongoDb
GET http://localhost:3000/m/mflix/users/_id/61745a912974aa86089d37c4

### MongoDb

###


###

PATCH http://localhost:3000/m/db/tbl/id/1

###


GET http://localhost:3000/m/mflix/users/_id/61745a912974aa86089d37c4
