# @name login
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}
###



@token={{login.response.body.token}}
###

# @name read
GET http://localhost:3000/schema/soap-movies/movies
    # ?filter={"id":3,"userName": "User 3"}
    # &filter={"country":"France"}
    # ?cache=300
authorization: Bearer {{token}}
###


###
# @name update
PATCH  http://localhost:3000/schema/soap-movies/movies
Content-Type: application/json
authorization: Bearer {{token}}

{
    "filter": {
        "id": 1
    },
    "data": {
        "title": "Fight Club",
        "description": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more."
    }
}

# ###
# # @name create
# POST  http://localhost:3000/schema/soap-movies/movies
# Content-Type: application/json
# authorization: Bearer {{token}}

# {
#     "data": {
#         "userName": "New User X",
#         "password": "123456"
#     }
# }

# ###
# # @name delete
# DELETE  http://localhost:3000/schema/soap-movies/movies
# Content-Type: application/json
# authorization: Bearer {{token}}
