# @name login
POST  http://127.0.0.1:3000/user/login
Content-Type: application/json

{
    "username":"myapiuser",
    "password": "myStr@ngpa$$w0rd"
}
###



@token={{login.response.body.token}}
###

# @name read
GET http://127.0.0.1:3000/schema/soap-movies/movie
    # ?filter={"id":3,"userName": "User 3"}
    # &filter={"country":"France"}
    # ?cache=300
authorization: Bearer {{token}}


###
# @name update
PATCH  http://127.0.0.1:3000/schema/soap-movies/movie
Content-Type: application/json
authorization: Bearer {{token}}

{
    "filter": {
        "id": 1
    },
    "data": {
        "title": "Hellraiser",
        "description": "Horror movie"
    }
}


###
# @name create
POST  http://127.0.0.1:3000/schema/soap-movies/movie
Content-Type: application/json
authorization: Bearer {{token}}

{
    "data": {
        "title": "Die Hard",
        "description": "Action movie",
        "releaseDate": "2023-01-01T00:00:00"
    }
}

###
# @name delete
DELETE  http://127.0.0.1:3000/schema/soap-movies/movie
Content-Type: application/json
authorization: Bearer {{token}}

{
    "filter-expression": "id > 2"
}