// Generated by CodiumAI

import { Convert } from '../Convert'

describe('Convert', () => {

    // OptionsFilterExpressionToSql method returns a string with SQL-like syntax from a filter expression string
    it('should return a string with SQL-like syntax when given a valid filter expression string', () => {
        const filterExpression = "field1 = 'value1' & field2 > 10"
        const expected = "field1 = 'value1'  AND  field2 > 10"

        const result = Convert.OptionsFilterExpressionToSql(filterExpression)

        expect(result).toEqual(expected)
    })

    // SqlSortToMongoSort method returns a MongoDB sort object from a SQL-like sort string
    it('should return a MongoDB sort object when given a valid SQL-like sort string', () => {
        const key = {}
        const value = "field1 ASC"
        const expected = {
            ...key,
            field1: 1
        }

        const result = Convert.SqlSortToMongoSort(key, value)

        expect(result).toEqual(expected)
    })

    // JsonToArray method returns an array of objects from a JSON object
    it('should return an array of objects when given a valid JSON object', () => {
        const obj = {
            field1: "value1",
            field2: "value2"
        }
        const expected = [
            { field1: "value1" },
            { field2: "value2" }
        ]

        const result = Convert.JsonToArray(obj)

        expect(result).toEqual(expected)
    })

    // JsonToArray method returns an empty array when given an empty JSON object
    it('should return an empty array when given an empty JSON object', () => {
        const obj = {}
        const expected: any = []

        const result = Convert.JsonToArray(obj)

        expect(result).toEqual(expected)
    })
})
