name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            ubuntu-22,
            ubuntu-latest,
            windows-latest,
            macos-latest,
            self-hosted,
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          NODE_NO_WARNINGS: 1
        with:
          ref: dev
      - name: Set up Node.js
        uses: actions/setup-node@v2
        env:
          NODE_NO_WARNINGS: 1
        with:
          node-version: "22.10.0"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Install typia
        run: npm run _typia-prepare || npm run typia-prepare
      - name: Compile
        run: npx tsc
      - name: run tests
        run: npm test
