name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      env:
        NODE_NO_WARNINGS: 1
      with:
        ref: dev
    - name: Set up Node.js
      uses: actions/setup-node@v2
      env:
        NODE_NO_WARNINGS: 1
      with:
        node-version: '22.10.0'
    - name: Install dependencies
      run: npm install
    - name: Install typia
      run: npm run _typia-prepare || npm run typia-prepare
    - name: Compile
      run: npx tsc
    - name: run tests
      run: npm test
