name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          [ubuntu-latest, windows-latest]
          # [ubuntu-22, ubuntu-latest, windows-latest, macos-latest, self-hosted]
        node:
          ["22.10.0", "22.11.0", "22.12.0", "22.13.0", "22.13.1", "22.14.0"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          NODE_NO_WARNINGS: 1
        with:
          ref: dev
      - name: Set up Node.js
        uses: actions/setup-node@v2
        env:
          NODE_NO_WARNINGS: 1
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Prepare
        run: npm run prepare
      - name: Compile
        run: npx tsc
      - name: run tests
        run: npm test
